packadges:
  - src/*

onlyBuiltDependencies:
  - unrs-resolver
catalog:
  "@commitlint/cli": ^20.1.0
  "@commitlint/config-conventional": ^20.0.0
  "@commitlint/types": ^20.0.0
  "@cspell/eslint-plugin": ^9.2.1
  "@eslint-react/eslint-plugin": 1.53.1
  "@flamework/components": ^1.2.2
  "@flamework/core": ^1.2.2
  "@flamework/networking": ^1.2.2
  "@isentinel/dict-rbxts": ^1.0.1
  "@isentinel/dict-roblox": ^1.0.3
  "@isentinel/eslint-config": ^3.3.0
  "@isentinel/tsconfig": ^1.0.0
  "@rbxts/cmdr": ^1.12.1
  "@rbxts/compiler-types": ^3.0.0-types.0
  "@rbxts/flamework-binary-serializer": ^0.7.0
  "@rbxts/janitor": 1.18.3-ts.0
  "@rbxts/lapis": ^0.3.8
  "@rbxts/lapis-mockdatastore": ^0.3.7
  "@rbxts/log": ^0.6.3
  "@rbxts/object-utils": ^1.0.4
  "@rbxts/pretty-react-hooks": ^0.6.4
  "@rbxts/rbx-better-signal": ^2.1.0
  "@rbxts/rbx-debug": 1.0.2-ts.0
  "@rbxts/react": ^17.2.3
  "@rbxts/react-roblox": ^17.2.3
  "@rbxts/remap": ^0.2.2
  "@rbxts/ripple": ^0.9.3
  "@rbxts/services": ^1.5.5
  "@rbxts/sift": ^0.0.11
  "@rbxts/t": ^3.2.1
  "@rbxts/types": ^1.0.777
  "@rbxts/ui-labs": ^2.4.1
  "@typescript-eslint/eslint-plugin": ^6.7.5
  "@typescript-eslint/parser": ^6.7.5
  eslint: ^9.37.0
  eslint-config-prettier: ^8.3.0
  eslint-plugin-pnpm: ^1.2.0
  eslint-plugin-prettier: ^3.4.0
  eslint-plugin-react-roblox-hooks: 5.1.0-rbx.1
  eslint-plugin-roblox-ts: ^0.0.30
  husky: ^9.1.7
  jiti: ^2.6.1
  prettier: ^2.3.2
  rbxts-transform-debug: ^2.2.0
  rbxts-transformer-flamework: ^1.2.2
  roblox-ts: ^2.3.0
  ts-plugin-sort-import-suggestions: ^1.0.4
  typescript: ^5.5.3
